//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmiKoWindows.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmiKoWindows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AmiKo Desitin.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to keine Arztadresse.
        /// </summary>
        public static string accountManagement {
            get {
                return ResourceManager.GetString("accountManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Addresse.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Addressbuch.
        /// </summary>
        public static string addressBook {
            get {
                return ResourceManager.GetString("addressBook", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AmiKo Desitin.
        /// </summary>
        public static string appTitle {
            get {
                return ResourceManager.GetString("appTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Artikel.
        /// </summary>
        public static string article {
            get {
                return ResourceManager.GetString("article", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        public static string beenden {
            get {
                return ResourceManager.GetString("beenden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Geburtstag.
        /// </summary>
        public static string birthdate {
            get {
                return ResourceManager.GetString("birthdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DD.MM.JJJJ.
        /// </summary>
        public static string birthdatePlaceholder {
            get {
                return ResourceManager.GetString("birthdatePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Geburtstag.
        /// </summary>
        public static string born {
            get {
                return ResourceManager.GetString("born", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wirkstoff / ATC Code.
        /// </summary>
        public static string butAtccode {
            get {
                return ResourceManager.GetString("butAtccode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inhaberin.
        /// </summary>
        public static string butAuthor {
            get {
                return ResourceManager.GetString("butAuthor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Volltext.
        /// </summary>
        public static string butFulltext {
            get {
                return ResourceManager.GetString("butFulltext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wirkstoff.
        /// </summary>
        public static string butIngredient {
            get {
                return ResourceManager.GetString("butIngredient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zulassungsnummer.
        /// </summary>
        public static string butRegnr {
            get {
                return ResourceManager.GetString("butRegnr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Therapie.
        /// </summary>
        public static string butTherapy {
            get {
                return ResourceManager.GetString("butTherapy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Präparat.
        /// </summary>
        public static string butTitle {
            get {
                return ResourceManager.GetString("butTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kat.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Interaktionen überprüfen.
        /// </summary>
        public static string checkInteractions {
            get {
                return ResourceManager.GetString("checkInteractions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wohnort.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bemerkungen.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kompendium.
        /// </summary>
        public static string compendium {
            get {
                return ResourceManager.GetString("compendium", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        public static string datei {
            get {
                return ResourceManager.GetString("datei", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EAN.
        /// </summary>
        public static string ean {
            get {
                return ResourceManager.GetString("ean", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fachinformation.
        /// </summary>
        public static string fachinfo {
            get {
                return ResourceManager.GetString("fachinfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string familyName {
            get {
                return ResourceManager.GetString("familyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Favoriten.
        /// </summary>
        public static string favorites {
            get {
                return ResourceManager.GetString("favorites", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to weiblich.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Geschlecht.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string givenName {
            get {
                return ResourceManager.GetString("givenName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Grösse in cm.
        /// </summary>
        public static string heightCm {
            get {
                return ResourceManager.GetString("heightCm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SwissMed.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Interaktionen.
        /// </summary>
        public static string interactions {
            get {
                return ResourceManager.GetString("interactions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CSV erstellen.
        /// </summary>
        public static string makeCsv {
            get {
                return ResourceManager.GetString("makeCsv", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PDF erstellen.
        /// </summary>
        public static string makePdf {
            get {
                return ResourceManager.GetString("makePdf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to männlich.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Medikamentenkorb.
        /// </summary>
        public static string medbasket {
            get {
                return ResourceManager.GetString("medbasket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string msgContactDeleteConfirmation {
            get {
                return ResourceManager.GetString("msgContactDeleteConfirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string msgContactSaveFailure {
            get {
                return ResourceManager.GetString("msgContactSaveFailure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string msgContactSaveSuccess {
            get {
                return ResourceManager.GetString("msgContactSaveSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string msgPrescriptionDeleteConfirmation {
            get {
                return ResourceManager.GetString("msgPrescriptionDeleteConfirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string msgPrescriptionFileFound {
            get {
                return ResourceManager.GetString("msgPrescriptionFileFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string msgPrescriptionImportFailure {
            get {
                return ResourceManager.GetString("msgPrescriptionImportFailure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string msgPrescriptionImportSuccess {
            get {
                return ResourceManager.GetString("msgPrescriptionImportSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string msgPrescriptionSavingContextConfirmation {
            get {
                return ResourceManager.GetString("msgPrescriptionSavingContextConfirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string msgProfileSaveFailure {
            get {
                return ResourceManager.GetString("msgProfileSaveFailure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string msgProfileUnsetWarning {
            get {
                return ResourceManager.GetString("msgProfileUnsetWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Neue Datenbank verfügbar!.
        /// </summary>
        public static string newDb {
            get {
                return ResourceManager.GetString("newDb", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Neues Rezept.
        /// </summary>
        public static string newPrescription {
            get {
                return ResourceManager.GetString("newPrescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie ein Produkt..
        /// </summary>
        public static string noclick {
            get {
                return ResourceManager.GetString("noclick", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keine Fachinformation in der Datenbank..
        /// </summary>
        public static string nofachinfo {
            get {
                return ResourceManager.GetString("nofachinfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to keine Packungen.
        /// </summary>
        public static string nopacks {
            get {
                return ResourceManager.GetString("nopacks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Packungen.
        /// </summary>
        public static string packs {
            get {
                return ResourceManager.GetString("packs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patientenverwaltung.
        /// </summary>
        public static string patientManagement {
            get {
                return ResourceManager.GetString("patientManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patient suchen.
        /// </summary>
        public static string patientSearch {
            get {
                return ResourceManager.GetString("patientSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Telefonnr.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pos.
        /// </summary>
        public static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rezepte.
        /// </summary>
        public static string prescription {
            get {
                return ResourceManager.GetString("prescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rezepte.
        /// </summary>
        public static string prescriptions {
            get {
                return ResourceManager.GetString("prescriptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preis.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drucken.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menge.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error Report.
        /// </summary>
        public static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pflichtfelder.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Suchresultat.
        /// </summary>
        public static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Überschreiben.
        /// </summary>
        public static string rewrite {
            get {
                return ResourceManager.GetString("rewrite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Suche.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Suche Patient....
        /// </summary>
        public static string searchPatient {
            get {
                return ResourceManager.GetString("searchPatient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unterschrift aus Datei.
        /// </summary>
        public static string selectPicture {
            get {
                return ResourceManager.GetString("selectPicture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Senden.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Abonnieren.
        /// </summary>
        public static string subscribe {
            get {
                return ResourceManager.GetString("subscribe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ungespeichert.
        /// </summary>
        public static string unsaved {
            get {
                return ResourceManager.GetString("unsaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aktualisieren.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gewicht in kg.
        /// </summary>
        public static string weightKg {
            get {
                return ResourceManager.GetString("weightKg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PLZ.
        /// </summary>
        public static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
